# Generated by Django 5.0.2 on 2024-04-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_newsletter_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
